### ISSUE TITLE
Upload

### ISSUE THREAD

**Issue by AppWerft** [appcelerator-modules/ti.urlsession#8]
Hi Hans,

is it possible to upload file in this URLsession?

**Comment by Sophrinix** [comment]
this question came up all the time when i was teaching the Appcelerator SDK fundamentals course. This module does not currently support uploading, but could very easily. ```uploadTaskWithRequest``` needs to be implemented.  https://developer.apple.com/reference/foundation/nsurlsession/1409763-uploadtaskwithrequest 

Here's an example of that api implemented in Objective-C. http://stackoverflow.com/questions/26123524/uploading-file-using-nsurlsessionuploadtask-to-php-server

**Comment by hansemannn** [comment]
Will be supported as part of #9, but non-official so far.
